[package]
name = "trash-man"
version = "0.1.0"
authors = ["Caleb Bassi <calebjbassi@gmail.com>"]
edition = "2018"

[[bin]]
name = "trash"
path = "src/main.rs"

[dependencies]
structopt = "0.2.14"
dirs = "1.0.4"
lazy_static = "1.2.0"
regex = "1.1.0"
promptly = "0.1.5"
xdg-trash = { path = "./xdg_trash" }
chrono = "0.4.6"
