[package]
name = "xdg-trash"
version = "0.1.0"
authors = ["Caleb Bassi <calebjbassi@gmail.com>"]
edition = "2018"

[dependencies]
platform-dirs = "0.1.0"
chrono = "0.4.6"
failure = "0.1.5"
path-clean = "0.1.0"
systemstat = "0.1.3"
nom = "5.0.0"
itertools = "0.8.0"
